# Generated by Django 2.1 on 2018-08-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_at',
            field=models.DateTimeField(),
        ),
    ]
